### ISSUE TITLE
Structure dissect Arrow Not Responding: How to Fix This Issue?

### ISSUE THREAD

**Issue by SaSukiTB** [kaijia2022/cheatengine-extended-sdk#1]
Has anyone else had this problem? Nothing happens when I click the Pointer arrow. Does anyone know how to fix it?
![Screenshot 2024-10-25 185018](https://github.com/user-attachments/assets/29a0c1d7-c141-4e7a-9bb3-63cc26c4305f)

**Comment by kaijia2022** [comment]
replace the dlls with the latest release of the other repo
